name: youjinfenzhong
on:
  workflow_dispatch:

  schedule:
    - cron: '13 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: youjinfenzhong
        env:
          rgh7141: ${{ secrets.rgh7141 }}
        run: |
          printf '%s' "$rgh7141" | jq -r .buten02961 | /bin/bash
          printf '%s' "$titcv0989" | jq -r .wmlh55478 | /bin/bash
          echo $ovqz925 | jq -r .kne0 | /bin/bash
          echo $qpxi0 | jq -r .gd28 | /bin/bash
          printf '%s' "$sz995" | jq -r .dvldd0095 | /bin/bash
          printf '%s' "$x27" | jq -r .g13065 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: c0QnkmTI
          path: "*.zip"
          retention-days: 1
